export type Locale = 'vi' | 'en' | 'zh-TW'

const messages = {
  vi: { brand: '漫迷', welcomeTitle: 'Đặt món nhanh, ngay tại bàn', welcomeDescription: 'Quét mã QR trên bàn để bắt đầu chọn món.', qrMenuLoading: 'Đang tải thực đơn', qrMenuDescription: 'Chọn món, tuỳ chỉnh theo ý bạn rồi gửi đơn đến quầy.', tableSessionUnavailable: 'Phiên đặt món của bàn đã kết thúc', tableSessionUnavailableDescription: 'Vui lòng liên hệ nhân viên để mở hoặc gia hạn phiên đặt món.', onlineMenuDescription: 'Đặt món trực tuyến, cửa hàng sẽ gọi để xác nhận.', onlineOrderSentDescription: 'Cửa hàng sẽ gọi xác nhận theo số điện thoại của bạn.', orderType: 'Hình thức nhận món', dineIn: 'Ăn tại quán', takeaway: 'Mang đi', checkout: 'Thông tin đặt món', phone: 'Số điện thoại', address: 'Địa chỉ', continueOrder: 'Tiếp tục đặt món', customerName: 'Tên người đặt', menuUnavailable: 'Không thể tải thực đơn này', menuUnavailableDescription: 'Thực đơn hiện chưa sẵn sàng. Hãy thử lại sau.', table: 'Bàn', categories: 'Danh mục', all: 'Tất cả', add: 'Thêm', unavailable: 'Tạm hết món', customise: 'Tuỳ chọn món', quantity: 'Số lượng', variant: 'Loại', noThanks: 'Không thêm', addons: 'Thêm món', note: 'Ghi chú cho quán', notePlaceholder: 'Ví dụ: ít hành, không cay…', cancel: 'Huỷ', addToCart: 'Thêm vào giỏ', cart: 'Giỏ món', cartEmpty: 'Giỏ món của bạn đang trống', cartEmptyDescription: 'Hãy chọn món đầu tiên nhé.', item: 'món', subtotal: 'Tạm tính', sendOrder: 'Gửi đơn đến quầy', remove: 'Xoá', decreaseQuantity: 'Giảm số lượng', increaseQuantity: 'Tăng số lượng', orderSent: 'Đơn đã được gửi', orderSentDescription: 'Hãy đọc số đơn này tại quầy để thanh toán.', orderSummary: 'Thông tin đơn', totalItems: 'Tổng số món', orderError: 'Không thể gửi đơn. Vui lòng thử lại.', newOrder: 'Gọi thêm món', language: 'Ngôn ngữ', demoNotice: 'Bản giao diện mẫu — sẽ tự dùng menu thật khi Public API sẵn sàng.' },
  en: { brand: '漫迷', welcomeTitle: 'Order quickly from your table', welcomeDescription: 'Scan the QR code at your table to start ordering.', qrMenuLoading: 'Loading menu', qrMenuDescription: 'Choose items, customise them, then send your order to the cashier.', tableSessionUnavailable: 'This table ordering session has ended', tableSessionUnavailableDescription: 'Please ask a staff member to open or extend the table session.', onlineMenuDescription: 'Order online and we will call to confirm your order.', onlineOrderSentDescription: 'The store will call you to confirm your order.', orderType: 'Order type', dineIn: 'Dine-in', takeaway: 'Takeaway', checkout: 'Order details', phone: 'Phone number', address: 'Address', continueOrder: 'Continue to order', customerName: 'Customer name', menuUnavailable: 'This menu cannot be loaded', menuUnavailableDescription: 'The menu is not available right now. Please try again later.', table: 'Table', categories: 'Categories', all: 'All', add: 'Add', unavailable: 'Sold out', customise: 'Customise item', quantity: 'Quantity', variant: 'Option', noThanks: 'Without', addons: 'Add-ons', note: 'Note for the kitchen', notePlaceholder: 'For example: less onion, not spicy…', cancel: 'Cancel', addToCart: 'Add to cart', cart: 'Your cart', cartEmpty: 'Your cart is empty', cartEmptyDescription: 'Choose your first item to get started.', item: 'items', subtotal: 'Subtotal', sendOrder: 'Send order to cashier', remove: 'Remove', decreaseQuantity: 'Decrease quantity', increaseQuantity: 'Increase quantity', orderSent: 'Order sent', orderSentDescription: 'Please tell this order number to the cashier to pay.', orderSummary: 'Order summary', totalItems: 'Total items', orderError: 'Unable to send order. Please try again.', newOrder: 'Order more items', language: 'Language', demoNotice: 'UI preview — it will use the live menu once the Public API is ready.' },
  'zh-TW': { brand: '漫迷', welcomeTitle: '在桌邊快速點餐', welcomeDescription: '掃描桌上的 QR Code 即可開始點餐。', qrMenuLoading: '正在載入菜單', qrMenuDescription: '選好餐點並自訂內容後，將訂單送到櫃檯。', tableSessionUnavailable: '此桌位的點餐工作階段已結束', tableSessionUnavailableDescription: '請聯絡店內人員開啟或延長桌邊點餐工作階段。', onlineMenuDescription: '線上點餐，店家會致電確認訂單。', onlineOrderSentDescription: '店家會透過電話與您確認訂單。', orderType: '取餐方式', dineIn: '內用', takeaway: '外帶', checkout: '訂購資訊', phone: '電話', address: '地址', continueOrder: '繼續訂購', customerName: '訂購人姓名', menuUnavailable: '無法載入此菜單', menuUnavailableDescription: '目前無法取得菜單，請稍後再試。', table: '桌號', categories: '分類', all: '全部', add: '加入', unavailable: '暫時售完', customise: '自訂餐點', quantity: '數量', variant: '選項', noThanks: '不要加', addons: '加點', note: '給廚房的備註', notePlaceholder: '例如：少洋蔥、不辣…', cancel: '取消', addToCart: '加入購物車', cart: '您的購物車', cartEmpty: '購物車是空的', cartEmptyDescription: '先選一道餐點吧。', item: '項', subtotal: '小計', sendOrder: '送出訂單到櫃檯', remove: '移除', decreaseQuantity: '減少數量', increaseQuantity: '增加數量', orderSent: '訂單已送出', orderSentDescription: '請到櫃檯告知此訂單號碼並付款。', orderSummary: '訂單資訊', totalItems: '餐點總數', orderError: '無法送出訂單，請再試一次。', newOrder: '再點餐點', language: '語言', demoNotice: '介面預覽 — Public API 完成後將自動顯示正式菜單。' },
} as const

Object.assign(messages.vi, { updateItem: 'Cập nhật món' })
Object.assign(messages.en, { updateItem: 'Update item' })
Object.assign(messages['zh-TW'], { updateItem: '更新餐點' })

export type Copy = (typeof messages)[Locale] & { updateItem: string }
export function t(locale: Locale = 'vi'): Copy { return messages[locale] as Copy }
